name: Notify portfolio hub

on:
  push:
    branches: [ main ]

# need write on repository_dispatch
permissions:
  contents: read
  repository_dispatch: write

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository dispatch via curl
        run: |
          curl -X POST https://api.github.com/repos/ddanrob/ddanrob-portfolio-hub/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.HUB_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"event_type":"content-updated","client_payload":{"ref":"'"${{ github.sha }}"'"}}'