name: Validate content


on:
  pull_request:
    paths:
      - "**/*.json"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.x.x

      - name: Install dependencies
        run: pnpm install --registry=https://registry.npmjs.org

      - name: Validate content
        run: pnpm run validate
