name: Validate content


on:
  pull_request:
    paths:
      - "**/*.json"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 7.5.0

      - name: Install dependencies
        run: pnpm install

      - name: Validate content
        run: pnpm run validate